name: 通过API同步上游（手动）
# 触发条件：仅手动触发（适合需要手动控制的场景）
on:
  workflow_dispatch:

jobs:
  api_sync_task:
    runs-on: ubuntu-latest
    steps:
      - name: 调用GitHub官方API同步上游
        uses: actions/github-script@v6  # 执行JavaScript脚本的工具
        with:
          script: |
            // 调用GitHub的mergeUpstream接口，自动同步上游仓库
            // 注意：该接口会自动关联你fork时的上游仓库（无需手动配置）
            await github.rest.repos.mergeUpstream({
              owner: context.repo.owner,  // 自动获取当前仓库的所有者（你的用户名）
              repo: context.repo.repo,    // 自动获取当前仓库的名称
              branch: 'main'              // 要同步到的分支（和上游主分支一致）
            })
