name: API同步（显示结果）
# 触发条件：仅手动触发，同步后会显示成功/失败日志
on:
  workflow_dispatch:

jobs:
  sync_and_show_result:
    runs-on: ubuntu-latest
    steps:
      - name: 同步上游并输出日志
        uses: actions/github-script@v6
        with:
          script: |
            try {
              // 尝试同步上游仓库
              const 结果 = await github.rest.repos.mergeUpstream({
                owner: context.repo.owner,
                repo: context.repo.repo,
                branch: 'main'
              })
              // 同步成功时，在日志里显示成功信息
              console.log('✅ 同步成功！返回结果：', 结果.data)
            } catch (错误) {
              // 同步失败时，在日志里显示错误原因
              console.log('❌ 同步失败：', 错误.message)
              // 如果失败就终止任务（避免显示“成功”）
              throw new Error('同步失败，请查看日志')
            }
