name: 通过Git同步上游（定时+手动）
# 触发条件：手动触发 + 每天UTC时间0点自动运行
on:
  workflow_dispatch:  # 手动触发按钮（在Actions页面点击运行）
  schedule:
    - cron: '0 0 * * *'  # 定时规则：每天运行一次

jobs:
  同步任务:
    runs-on: ubuntu-latest  # 使用GitHub提供的Ubuntu系统
    steps:
      - name: 拉取当前仓库代码
        uses: actions/checkout@v4  # 官方拉取代码的工具
        with:
          fetch-depth: 0  # 拉取所有历史提交，避免同步时冲突

      - name: 配置Git身份（用于提交代码）
        run: |
          # 设置提交者名称和邮箱（GitHub Actions默认身份）
          git config user.name "GitHub自动同步"
          git config user.email "actions@github.com"

      - name: 同步上游仓库到当前仓库
        run: |
          # 添加上游仓库地址（替换成你的上游仓库，比如https://github.com/原作者/原仓库.git）
          git remote add 上游仓库 https://github.com/abbasvd3/clash.git || true
          # 拉取上游仓库的最新代码
          git fetch 上游仓库
          # 合并上游仓库的main分支到当前仓库的main分支（无需手动编辑提交信息）
          git merge 上游仓库/main --no-edit
          # 把合并后的代码推送到自己的仓库
          git push origin main
