name: Sync with Git (Manual & Schedule)
on:
  workflow_dispatch:  # 手动触发（在 Actions 页面点“Run workflow”）
  schedule:
    - cron: '0 8 * * *'  # 每天北京时间 16 点自动同步（UTC+8，按需改）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取当前仓库代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取所有历史，避免冲突

      - name: 配置 Git 身份
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: 同步上游仓库代码
        run: |
          # 替换成你的上游仓库地址（比如 https://github.com/abbasvd3/clash.git）
          UPSTREAM_REPO="https://github.com/上游用户名/上游仓库名.git"
          # 添加上游仓库（若已添加则忽略）
          git remote add upstream $UPSTREAM_REPO || true
          # 拉取上游最新代码
          git fetch upstream
          # 合并到当前分支（默认 main，若你的分支是 master 就改这里）
          git merge upstream/main --no-edit
          # 推送到自己的仓库
          git push origin main
