# 工作流总名称（中文显示，在Actions列表中可见）
name: 自动同步上游仓库

# 权限配置：允许写入仓库内容
permissions:
  contents: write

# 触发条件：定时+手动触发
on:
  schedule:
    - cron: "0 6 * * *"  # 每天UTC 6点（北京时间14点）自动运行
  workflow_dispatch:     # 支持在GitHub页面手动触发

# 任务配置（核心修复：任务ID用英文，显示名称用中文）
jobs:
  # 任务ID（必须英文/数字/下划线/连字符，这是规则）
  sync_upstream_code:
    # 任务显示名称（中文，在运行详情中可见）
    name: 同步上游仓库最新代码
    runs-on: ubuntu-latest  # 运行环境
    if: ${{ github.event.repository.fork }}  # 仅Fork仓库运行

    steps:
      # 步骤1：检出当前仓库代码
      - name: 检出当前仓库
        uses: actions/checkout@v4

      # 步骤2：同步上游仓库（核心步骤）
      - name: 同步上游仓库代码
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: abbasdvd3/clash  # 目标上游仓库
          upstream_sync_branch: main           # 上游仓库分支（按需修改）
          target_sync_branch: main             # 本地同步分支
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      # 步骤3：同步失败提示
      - name: 同步失败处理
        if: failure()
        run: |
          echo "[错误] 同步失败，请手动检查或同步仓库。"
          exit 1
