# 工作流名称（中文）
name: 自动同步上游仓库

permissions:
  contents: write

on:
  schedule:
    - cron: "0 6 * * *"  # 每天UTC 6点（北京时间14点）运行
  workflow_dispatch:

jobs:
  # 任务名称也用中文
  同步上游代码:
    name: 同步上游仓库最新代码
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      - name: 检出当前仓库
        uses: actions/checkout@v4

      - name: 同步 abbasdvd3/clash 代码
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: abbasdvd3/clash
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: 同步失败处理
        if: failure()
        run: |
          echo "[错误] 同步失败，请手动检查或同步仓库。"
          exit 1
